new scanner
SIWECOS/translations pull request #33
Opened 2019-10-25 14:51 UTC by PetraStruck

Anbei die Texte für die neuen Scanner

2019-10-25 15:31 UTC, Skeeve requested changes
Duplicate Link Bleichenbacher-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/BLEICHENBACHER_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/BLEICHENBACHER_VULNERABLE/Link/en.wiki
Duplicate Link Certificate-Expired-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CERTIFICATE_EXPIRED/Link/en.wiki
  and /home/scripts/texts/IMAP/CERTIFICATE_EXPIRED/Link/en.wiki
Duplicate Link Certificate-Not-Sent-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CERTIFICATE_NOT_SENT_BY_SERVER/Link/en.wiki
  and /home/scripts/texts/IMAP/CERTIFICATE_NOT_SENT_BY_SERVER/Link/en.wiki
Duplicate Link Certificate-Not-Valid-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CERTIFICATE_NOT_VALID_YET/Link/en.wiki
  and /home/scripts/texts/IMAP/CERTIFICATE_NOT_VALID_YET/Link/en.wiki
Duplicate Link Weak-Encryption-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CERTIFICATE_WEAK_HASH_FUNCTION/Link/en.wiki
  and /home/scripts/texts/IMAP/CERTIFICATE_WEAK_HASH_FUNCTION/Link/en.wiki
Duplicate Link Encryption-Algorithms-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITEORDER_ENFORCED/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITEORDER_ENFORCED/Link/en.wiki
Duplicate Link Key-Exchange-Method-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITE_ANON/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITE_ANON/Link/en.wiki
Duplicate Link Weak-DE-Encryption-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITE_DES/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITE_DES/Link/en.wiki
Duplicate Link Weakened-Encryption-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITE_EXPORT/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITE_EXPORT/Link/en.wiki
Duplicate Link Unencrypted-Communication-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITE_NULL/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITE_NULL/Link/en.wiki
Duplicate Link Unsecure-RC4-Encryption-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CIPHERSUITE_RC4/Link/en.wiki
  and /home/scripts/texts/IMAP/CIPHERSUITE_RC4/Link/en.wiki
Duplicate Link Crime-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/CRIME_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/CRIME_VULNERABLE/Link/en.wiki
Duplicate Link Early-CCS-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/EARLYCCS_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/EARLYCCS_VULNERABLE/Link/en.wiki
Duplicate Link Heartbleed-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/HEARTBLEED_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/HEARTBLEED_VULNERABLE/Link/en.wiki
Duplicate Link No-TLS-Support-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/HTTPS_NOT_SUPPORTED/Link/en.wiki
  and /home/scripts/texts/IMAP/HTTPS_NOT_SUPPORTED/Link/en.wiki
Duplicate Link Response-Time-Exceeded-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/HTTPS_NO_RESPONSE/Link/en.wiki
  and /home/scripts/texts/IMAP/HTTPS_NO_RESPONSE/Link/en.wiki
Duplicate Link Invalid-Curve-Eephemeral-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/en.wiki
Duplicate Link Invalid-Curve-Vulnerabilty-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/INVALID_CURVE_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/INVALID_CURVE_VULNERABLE/Link/en.wiki
Duplicate Link PADDING-ORACLE-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/PADDING_ORACLE_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/PADDING_ORACLE_VULNERABLE/Link/en.wiki
Duplicate Link POODLE-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/POODLE_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/POODLE_VULNERABLE/Link/en.wiki
Duplicate Link Obsolete-Protocol-Version-SSL2-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/PROTOCOLVERSION_SSL2/Link/en.wiki
  and /home/scripts/texts/IMAP/PROTOCOLVERSION_SSL2/Link/en.wiki
Duplicate Link Obsolete-Protocol-Version-SSL3-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/PROTOCOLVERSION_SSL3/Link/en.wiki
  and /home/scripts/texts/IMAP/PROTOCOLVERSION_SSL3/Link/en.wiki
Duplicate Link Protocol-Version-TLS13-Found-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/PROTOCOLVERSION_TLS13/Link/en.wiki
  and /home/scripts/texts/IMAP/PROTOCOLVERSION_TLS13/Link/en.wiki
Duplicate Link Sweet32-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/SWEET32_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/SWEET32_VULNERABLE/Link/en.wiki
Duplicate Link TLS-POODLE-Vulnerability-IMAPS/EN defined
  in  /home/scripts/texts/IMAPS/TLS_POODLE_VULNERABLE/Link/en.wiki
  and /home/scripts/texts/IMAP/TLS_POODLE_VULNERABLE/Link/en.wiki
Duplicate Link Bleichenbacher-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/BLEICHENBACHER_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/BLEICHENBACHER_VULNERABLE/Link/de.wiki
Duplicate Link Zertifikat-Abgelaufen/DE defined
  in  /home/scripts/texts/SMTP/CERTIFICATE_EXPIRED/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_EXPIRED/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gesendet/DE defined
  in  /home/scripts/texts/SMTP/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gueltig/DE defined
  in  /home/scripts/texts/SMTP/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
Duplicate Link Schwache-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
Duplicate Link Verschl�sselungsalgorithmen/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
Duplicate Link Schluesselaustauschverfahren/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITE_ANON/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_ANON/Link/de.wiki
Duplicate Link Schwache-DES-Verschl�sselung/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITE_DES/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_DES/Link/de.wiki
Duplicate Link Geschwaechte-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITE_EXPORT/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_EXPORT/Link/de.wiki
Duplicate Link Unverschluesselte-Kommunikation/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITE_NULL/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_NULL/Link/de.wiki
Duplicate Link Unsichere-RC4-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP/CIPHERSUITE_RC4/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_RC4/Link/de.wiki
Duplicate Link Crime-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/CRIME_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/CRIME_VULNERABLE/Link/de.wiki
Duplicate Link Early-CCS-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/EARLYCCS_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/EARLYCCS_VULNERABLE/Link/de.wiki
Duplicate Link Heartbleed-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/HEARTBLEED_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/HEARTBLEED_VULNERABLE/Link/de.wiki
Duplicate Link Keine-TLS-Unterstuetzung/DE defined
  in  /home/scripts/texts/SMTP/HTTPS_NOT_SUPPORTED/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NOT_SUPPORTED/Link/de.wiki
Duplicate Link Antwortzeit-Ueberschritten/DE defined
  in  /home/scripts/texts/SMTP/HTTPS_NO_RESPONSE/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NO_RESPONSE/Link/de.wiki
Duplicate Link Invalid-Curve-Ephemeral-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/de.wiki
Duplicate Link Invalid-Curve-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP/INVALID_CURVE [...]

2019-10-25 15:31 UTC, Skeeve commented
dir2wiki beschwert sich

2019-10-25 21:06 UTC, Skeeve commented
Nach den Korrekturen:

```
$ dir2wiki -d
Reading templates
Checking required sections
Reading Test texts
Reading Wiki texts
Checking Test translations
Checking Wiki translations
Parsing pages
Duplicate Link Bleichenbacher-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/BLEICHENBACHER_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/BLEICHENBACHER_VULNERABLE/Link/de.wiki
Duplicate Link Zertifikat-Abgelaufen/DE defined
  in  /home/scripts/texts/SMTPS/CERTIFICATE_EXPIRED/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_EXPIRED/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gesendet/DE defined
  in  /home/scripts/texts/SMTPS/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gueltig/DE defined
  in  /home/scripts/texts/SMTPS/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
Duplicate Link Schwache-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTPS/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
Duplicate Link Verschl�sselungsalgorithmen/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
Duplicate Link Schluesselaustauschverfahren/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITE_ANON/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_ANON/Link/de.wiki
Duplicate Link Schwache-DES-Verschl�sselung/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITE_DES/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_DES/Link/de.wiki
Duplicate Link Geschwaechte-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITE_EXPORT/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_EXPORT/Link/de.wiki
Duplicate Link Unverschluesselte-Kommunikation/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITE_NULL/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_NULL/Link/de.wiki
Duplicate Link Unsichere-RC4-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTPS/CIPHERSUITE_RC4/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_RC4/Link/de.wiki
Duplicate Link Crime-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/CRIME_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/CRIME_VULNERABLE/Link/de.wiki
Duplicate Link Early-CCS-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/EARLYCCS_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/EARLYCCS_VULNERABLE/Link/de.wiki
Duplicate Link Heartbleed-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/HEARTBLEED_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/HEARTBLEED_VULNERABLE/Link/de.wiki
Duplicate Link Keine-TLS-Unterstuetzung/DE defined
  in  /home/scripts/texts/SMTPS/HTTPS_NOT_SUPPORTED/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NOT_SUPPORTED/Link/de.wiki
Duplicate Link Antwortzeit-Ueberschritten/DE defined
  in  /home/scripts/texts/SMTPS/HTTPS_NO_RESPONSE/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NO_RESPONSE/Link/de.wiki
Duplicate Link Invalid-Curve-Ephemeral-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/INVALID_CURVE_EPHEMERAL_VULNERABLE/Link/de.wiki
Duplicate Link Invalid-Curve-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/INVALID_CURVE_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/INVALID_CURVE_VULNERABLE/Link/de.wiki
Duplicate Link PADDING-ORACLE-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/PADDING_ORACLE_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/PADDING_ORACLE_VULNERABLE/Link/de.wiki
Duplicate Link POODLE-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/POODLE_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/POODLE_VULNERABLE/Link/de.wiki
Duplicate Link Veraltete-Protokollversion-SSL2/DE defined
  in  /home/scripts/texts/SMTPS/PROTOCOLVERSION_SSL2/Link/de.wiki
  and /home/scripts/texts/POP3S/PROTOCOLVERSION_SSL2/Link/de.wiki
Duplicate Link Veraltete-Protokollversion-SSL3/DE defined
  in  /home/scripts/texts/SMTPS/PROTOCOLVERSION_SSL3/Link/de.wiki
  and /home/scripts/texts/POP3S/PROTOCOLVERSION_SSL3/Link/de.wiki
Duplicate Link Protokollversion-TLS13-Gefunden/DE defined
  in  /home/scripts/texts/SMTPS/PROTOCOLVERSION_TLS13/Link/de.wiki
  and /home/scripts/texts/POP3S/PROTOCOLVERSION_TLS13/Link/de.wiki
Duplicate Link Sweet32-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/SWEET32_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/SWEET32_VULNERABLE/Link/de.wiki
Duplicate Link TLS-POODLE-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTPS/TLS_POODLE_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/TLS_POODLE_VULNERABLE/Link/de.wiki
Duplicate Link Bleichenbacher-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP_MSA/BLEICHENBACHER_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/BLEICHENBACHER_VULNERABLE/Link/de.wiki
Duplicate Link Zertifikat-Abgelaufen/DE defined
  in  /home/scripts/texts/SMTP_MSA/CERTIFICATE_EXPIRED/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_EXPIRED/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gesendet/DE defined
  in  /home/scripts/texts/SMTP_MSA/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_SENT_BY_SERVER/Link/de.wiki
Duplicate Link Zertifikat-Nicht-Gueltig/DE defined
  in  /home/scripts/texts/SMTP_MSA/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_NOT_VALID_YET/Link/de.wiki
Duplicate Link Schwache-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP_MSA/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
  and /home/scripts/texts/POP3S/CERTIFICATE_WEAK_HASH_FUNCTION/Link/de.wiki
Duplicate Link Verschl�sselungsalgorithmen/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITEORDER_ENFORCED/Link/de.wiki
Duplicate Link Schluesselaustauschverfahren/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITE_ANON/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_ANON/Link/de.wiki
Duplicate Link Schwache-DES-Verschl�sselung/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITE_DES/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_DES/Link/de.wiki
Duplicate Link Geschwaechte-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITE_EXPORT/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_EXPORT/Link/de.wiki
Duplicate Link Unverschluesselte-Kommunikation/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITE_NULL/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_NULL/Link/de.wiki
Duplicate Link Unsichere-RC4-Verschluesselung/DE defined
  in  /home/scripts/texts/SMTP_MSA/CIPHERSUITE_RC4/Link/de.wiki
  and /home/scripts/texts/POP3S/CIPHERSUITE_RC4/Link/de.wiki
Duplicate Link Crime-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP_MSA/CRIME_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/CRIME_VULNERABLE/Link/de.wiki
Duplicate Link Early-CCS-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP_MSA/EARLYCCS_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/EARLYCCS_VULNERABLE/Link/de.wiki
Duplicate Link Heartbleed-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP_MSA/HEARTBLEED_VULNERABLE/Link/de.wiki
  and /home/scripts/texts/POP3S/HEARTBLEED_VULNERABLE/Link/de.wiki
Duplicate Link Keine-TLS-Unterstuetzung/DE defined
  in  /home/scripts/texts/SMTP_MSA/HTTPS_NOT_SUPPORTED/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NOT_SUPPORTED/Link/de.wiki
Duplicate Link Antwortzeit-Ueberschritten/DE defined
  in  /home/scripts/texts/SMTP_MSA/HTTPS_NO_RESPONSE/Link/de.wiki
  and /home/scripts/texts/POP3S/HTTPS_NO_RESPONSE/Link/de.wiki
Duplicate Link Invalid-Curve-Ephemeral-Schwachstelle/DE defined
  in  /home/scripts/texts/SMTP_MSA/INVA [...]

2019-10-26 11:13 UTC, PetraStruck commented
Jetzt sollte alles passen, dir2wiki ist komplett ohne Probleme durchgelaufen.

2019-10-26 22:27 UTC, Skeeve commented
Missing link: Certificates in IMAP: CERTIFICATE_EXPIRED: Solution_Tips (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in IMAP: INVALID_CURVE_EPHEMERAL_VULNERABLE: Positive (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in IMAP: INVALID_CURVE_EPHEMERAL_VULNERABLE: Negative (en).
Missing link: Invalid Curve Vulnerability/EN in IMAP: INVALID_CURVE_VULNERABLE: Positive (en).
Missing link: Invalid Curve Vulnerability/EN in IMAP: INVALID_CURVE_VULNERABLE: Negative (en).
Missing link: TLS in IMAP: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in IMAP: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in IMAP: Resulttext HTTPS_RESPONSE (de).
Missing link: Certificates in IMAPS: CERTIFICATE_EXPIRED: Solution_Tips (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in IMAPS: INVALID_CURVE_EPHEMERAL_VULNERABLE: Positive (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in IMAPS: INVALID_CURVE_EPHEMERAL_VULNERABLE: Negative (en).
Missing link: Invalid Curve Vulnerability/EN in IMAPS: INVALID_CURVE_VULNERABLE: Positive (en).
Missing link: Invalid Curve Vulnerability/EN in IMAPS: INVALID_CURVE_VULNERABLE: Negative (en).
Missing link: TLS in IMAPS: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in IMAPS: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in IMAPS: Resulttext HTTPS_RESPONSE (de).
Missing link: TLS in POP3: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in POP3: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in POP3S: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in POP3S: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in POP3S: Resulttext HTTPS_RESPONSE (de).
Missing link: Certificates in SMTP: CERTIFICATE_EXPIRED: Solution_Tips (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTP: INVALID_CURVE_EPHEMERAL_VULNERABLE: Positive (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTP: INVALID_CURVE_EPHEMERAL_VULNERABLE: Negative (en).
Missing link: Invalid Curve Vulnerability/EN in SMTP: INVALID_CURVE_VULNERABLE: Positive (en).
Missing link: Invalid Curve Vulnerability/EN in SMTP: INVALID_CURVE_VULNERABLE: Negative (en).
Missing link: TLS in SMTP: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in SMTP: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in SMTP: Resulttext HTTPS_RESPONSE (de).
Missing link: Certificates in SMTP_MSA: CERTIFICATE_EXPIRED: Solution_Tips (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTP_MSA: INVALID_CURVE_EPHEMERAL_VULNERABLE: Positive (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTP_MSA: INVALID_CURVE_EPHEMERAL_VULNERABLE: Negative (en).
Missing link: Invalid Curve Vulnerability/EN in SMTP_MSA: INVALID_CURVE_VULNERABLE: Positive (en).
Missing link: Invalid Curve Vulnerability/EN in SMTP_MSA: INVALID_CURVE_VULNERABLE: Negative (en).
Missing link: TLS in SMTP_MSA: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in SMTP_MSA: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in SMTP_MSA: Resulttext HTTPS_RESPONSE (de).
Missing link: Certificates in SMTPS: CERTIFICATE_EXPIRED: Solution_Tips (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTPS: INVALID_CURVE_EPHEMERAL_VULNERABLE: Positive (en).
Missing link: Invalid Curve Ephemeral Vulnerability/EN in SMTPS: INVALID_CURVE_EPHEMERAL_VULNERABLE: Negative (en).
Missing link: Invalid Curve Vulnerability/EN in SMTPS: INVALID_CURVE_VULNERABLE: Positive (en).
Missing link: Invalid Curve Vulnerability/EN in SMTPS: INVALID_CURVE_VULNERABLE: Negative (en).
Missing link: TLS in SMTPS: CERTIFICATE_EXPIRED: Description (de).
Missing link: TLS in SMTPS: CERTIFICATE_NOT_VALID_YET: Description (de).
Missing link: TLS in SMTPS: Resulttext HTTPS_RESPONSE (de).

2019-10-27 13:58 UTC, Skeeve approved these changes

2019-10-27 13:58 UTC, merged